### ISSUE TITLE
Minimize sensor data sending speed

### ISSUE THREAD

**Issue by N1N** [fenrir-naru/ninja-scan-light#10]
Hi,

I am using NinjaScan light sensor in linux. I want to capture the live sensor data.
As per my requirement,i want the sensor device to send the data exactly after 1 second,not before that.
In my application i am using read() with /dev/ttyACM0 node.

How to reduce the data sending speed of Sensor device.

Regards,
NaN

**Comment by fenrir-naru** [comment]
Thank you for your comment.

The difficulty to answer your question quite depends on how precise "1 second" you said is (for instance +/- 1ns?).
At least, you have to consider the following things;
- Synchronization between OS managed time and standard time represented by UTC, or GPS time.
- How precise OS provided time functions such as sleep() is.
- IO mechanism; consideration of use of non-blocking IO.

AGAIN, I cannot provide any sufficient support for Linux, therefore, I will close this issue. If you can resolve the problem by yourself, please let me know by writing additional comments to share the know-how.

**Comment by N1N** [comment]
@fenrir-naru 

Thank you for the reply.

I just want to set the time interval in the sensor device,
For ex: If i set 2 seconds, the sensor device should send the data every 2 seconds.
If i go for read() before 2 seconds, sensor device should not give the data.
Any commands available to set the time interval,so that i can get the data every 'n' seconds?

Regards,
NaN

**Comment by fenrir-naru** [comment]
I understood what you wanted to do. You want to reduce the output frequency of data from NinjaScan-Light.
I think the easiest way is to build a small Linux program to filter out data which is redundant for you, rather than to modify the firmware.

**Comment by N1N** [comment]
Thank you.

I need to know one more information.
Whether NinjaScan supports CTS-RTS handshaking?
If yes, how to enable that?

Regards,
NaN

**Comment by fenrir-naru** [comment]
I understand your case more clearly.
Currently, the SW/HW flow control capability like CTS-RTS, XON-XOFF has not been implemented. Moreover, I do not have any plan to do so in the future, because I designed the device to transmit data as much as possible.
Probably, the problem will be solved by improving your program. You had better to split the tasks of reading data from the other tasks by using multi-thread programming technique. The read task should always read data in order to reduce the possibility to encounter the buffer overflow.

**Comment by N1N** [comment]
@fenrir-naru
I understand your suggestions.
But i am continuously reading the data without doing any other task. even then bytes are being lost. 
If s/w and h/w flow control is not supported, then only reducing the output frequency of ninja scan device will solve the issue. 
So can u please tell how to reduce output frequency? 
Regards, 
NaN

**Comment by fenrir-naru** [comment]
The firmware modification might be difficult for you, because of both of your skill ( you have to understand the C code for 8051 microprocessor, which is unpopular unlike Arduino) and environment (you need additional debug hardware and circuit to download the modified firmware to the target).
Therefore, I strongly recommend to check your program first. please share your source code.

**Comment by N1N** [comment]
@fenrir-naru  

Please find the code below, which i am using to get data from ninja scan device. As i told u before, i am not doing other tasks, other than reading from the device.

I am running this code in ARM imx processor board.

int main(){
 int i = 0;
 struct termios options;
 int count = 100;
 u_int8_t sentence[2500]="";
 static const char fileSource[] ="/dev/ttyACM0";
 int counter=0;
 int fd = open(fileSource,O_RDONLY);
int in = 0;
while(count>0){
if(in>999)
break;
 counter=read(fd, sentence+in,1000);
 printf("counter %d\n",counter);
 in += counter;

count--;
}
 for(i=0;i<in;i++)
    printf("sentence[%d] %x\n",i,sentence[i]);

return 0;
}

**Comment by fenrir-naru** [comment]
Thank you for sharing your code.
Could you tell me how you recognize the data is lost? One confirmation, do you know there is DIFFERENCE between the data logged to MicroSD and streamed on USB? Please check Wiki. https://github.com/fenrir-naru/ninja-scan-light/wiki/USBSerialDumpFormat 

BTW, you had better to use some syntax high-lighten code sharing site such as Gist https://gist.github.com/ .

**Comment by fenrir-naru** [comment]
I found a cause in your code. You have to configure termios struct as "raw" mode in order to receiver binary data without any interrupt. Please google cfmakeraw(), or see http://linuxmemonote.blogspot.jp/2010/07/linuxrs-232crs-422ttyraw.html if you can read Japanese. Also as reference, I use the following configuration for my program. https://github.com/fenrir-naru/ninja-scan-light/blob/master/tool/util/comstream.h#L319
