### ISSUE TITLE
Data from telemetry connector

### ISSUE THREAD

**Issue by takespace** [fenrir-naru/ninja-scan-light#13]
Hi, I'm using chotto-sugoi logger with telemetry connector.
That's is powerful function but I got some data including data.

I couldn't get correct ubx data.
Byte data after 0x47('G')  is always 0x00.
In the same time, data from SD card is always correct.

Any body have same problem?

**Comment by fenrir-naru** [comment]
Hi, thank you for your sharing the problem.
I am interested in this issue.
I want to investigate the problem more, so could you upload the SD and telemetry data which include the problem anywhere?

**Comment by takespace** [comment]
Thank you for your reply.
It's OK, but it include private information....GPS data.

I found your e-mail address on blog site.
I sent you the text file.

Could you check it?

**Comment by fenrir-naru** [comment]
Thank you, I received your data. I will check it.
When I have progress, I will comment here.

**Comment by takespace** [comment]
Thank you for your kind.
I also try to solve this issue.
See you then.

**Comment by fenrir-naru** [comment]
I saw the data you sent me.
I agree with you that the good data being in the SD but the corrupted data being in the telemetry is also strange for me.
This type of a problem should be tackled by testing possibilities one by one.
The first step is the hardware; if you use a wireless system for the telemetry, please change it to the wired, that is, direct connection and check data again?

**Comment by takespace** [comment]
I got the data by FTDI<->USB adapter not wireless system.
If hardware has a problem, Page checksum will not be match.

When I check the checksum of the G page, those were totally matched.
But UBX data by those G page data did not match.
So I think it has issue before making G page check sum.
How is my guess?

**Comment by fenrir-naru** [comment]
Thank you for already checking the first step. There is no problem in the hardware.
So the second step is the data amount.
I am concerned that if the telemetry data is larger than expected, it will be lost due to the slower UART rate than that of SD.
To check the possibility, could you change the content of the telemetry by putting "renew.cfg" generated with a Ruby script [renew_cfg_gen.rb](https://github.com/fenrir-naru/ninja-scan-light/blob/master/firmware/misc/renew_cfg_gen.rb) in a SD card. The 143rd to 145th lines of renew_cfg_gen.rb regulates A/P/M page  frequencies, respectively. The larger number means less frequency, therefore, 255 is the best choice for this situation.
I hope the above information is helpful to solve the problem.

**Comment by fenrir-naru** [comment]
@takespace Thank you for another data, I checked it.
The data was very helpful, and I found a bug, which was clearly related to this issue.
The bug was careless, however, critical.
I fixed it with c1ea36f, please check the latest master branch including it.

**Comment by fenrir-naru** [comment]
I have checked the bug fix with my hardware, and I successfully read the G page via telemetry.
A new release [v1.1.2+firmware](https://github.com/fenrir-naru/ninja-scan-light/releases/tag/v1.1.2%2BFirmware) includes the bug fix, and I will close this issue.
@takespace , if you find trouble associated with this issue, please reopen it.

**Comment by takespace** [comment]
Sorry for my late reply.
I checked the firmware.
It completely worked!!

I have 1 more other issue.
I'll contact you as other issue.
Thank you so much.
