### ISSUE TITLE
Ninjascan-light not sending data - Green and Blue LED blinking

### ISSUE THREAD

**Issue by N1N** [fenrir-naru/ninja-scan-light#9]
Hi,

I have Ninjascan-light sensor. Initially when i connected to my PC (running UBUNTU),
With the below command,
 cat /dev/ttyACM0
i was able to get the log data in to my terminal.

After sometime,it stopped sending data.But both green and blue LED's are blinking.

I tried reconnecting the device several times, but the result is same. It is getting detected as ACM0,Green and blue LED's are blinking but it is not sending any data.

Also i am getting following print in dmesg,
"string descriptor 0 read error: -32"

Please help!

Regards,
NaN

**Comment by fenrir-naru** [comment]
Hi, thank you for sending me a feedback. Probably, it is a complex problem related to CDC driver and it may not a case that my developed device is just evil.
It is difficult for me to help you because I mostly focus on Windows. However, if you let me know more detail, such as packet capture of USB bus, it is great helpful.
